version: '3.7'
services:
  rpx:
    build:
      context: nginx/
    volumes: 
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./ssl
        target: /etc/ssl
        read_only: true
    networks:
      - byappt
    ports:
      - "80:80"
      - "443:443"

  jenkins:
    image: jenkins/jenkins
    expose: 
      - "8080"
    volumes:
    - type: volume
      source: jenkins_home
      target: /var/jenkins_home
    networks:
      - byappt

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
      labels:
        co.elastic.logs/module: "elasticsearch"
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data 
    expose:
      - "9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - byappt

volumes:
  jenkins_home:
  elasticsearch:

networks:
  byappt:
    
