version: '3.7'
services:
  rpx:
    build:
      context: nginx/
    labels:
        co.elastic.logs/module: "nginx"
        co.elastic.logs/fileset.stdout: "access"
        co.elastic.logs/fileset.stderr: "error"
    volumes: 
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./ssl
        target: /etc/ssl
        read_only: true
    networks:
      - byappt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - jenkins
      - kibana

  jenkins:
    image: jenkins/jenkins
    expose: 
      - "8080"
    volumes:
    - type: volume
      source: jenkins_home
      target: /var/jenkins_home
    networks:
      - byappt

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
      labels:
        co.elastic.logs/module: "elasticsearch"
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data 
    expose:
      - "9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - byappt

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    labels:
        co.elastic.logs/module: "kibana"
    volumes:
      - type: bind
        source: ./kibana/config
        target: /usr/share/kibana/config
        read_only: true
    expose:
      - "5601"
    networks:
      - byappt
    depends_on:
      - elasticsearch

  filebeat:
    user: root
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    command: filebeat -e -strict.perms=false -E output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes: 
      - type: bind
        source: ./filebeat/filebeat.docker.yml
        target: /usr/share/filebeat/filebeat.ym
        read_only: true
      - type: bind
        source: ./filebeat/modules.d
        target: /usr/share/filebeat/modules.
        read_only: true
      - type: bind
        source: /var/snap/docker/common/var-lib-docker
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - byappt
    depends_on:
      - elasticsearch

volumes:
  jenkins_home:
  elasticsearch:

networks:
  byappt:
    
