version: '3.7'
services:
  jenkins:
    build:
      context: jenkins/
    image: jenkins/jenkins
    labels:
      co.elastic.logs/processors.dissect.tokenizer:  "%{?year} %{?time} [id=%{id}]\t%{level}\t%{logger}#%{event}: %{message}"
    expose: 
      - "8080"
    volumes:
    - type: volume
      source: jenkins_home
      target: /var/jenkins_home
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
    networks:
      - jenkins

volumes:
  jenkins_home:
  elasticsearch:
  filebeat:

networks:
  jenkins:
    
